pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'netra2608/jenkins-demo'     // change if needed
        AWS_HOST = 'ec2-user@13.232.202.98'     // fill later
        AWS_KEY  = credentials('aws-key')              // Jenkins credential ID
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/netra2602/jenkins-practical.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the project...'
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging the build...'
                sh 'mvn package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh "docker build -t ${DOCKER_HUB_REPO}:latest ."
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker push ${DOCKER_HUB_REPO}:latest"
                }
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                echo 'Deploying container to EC2...'
                sh """
                ssh -o StrictHostKeyChecking=no -i ${AWS_KEY} ${AWS_HOST} '
                    docker pull ${DOCKER_HUB_REPO}:latest &&
                    docker stop myapp || true &&
                    docker rm myapp || true &&
                    docker run -d --name myapp -p 80:80 ${DOCKER_HUB_REPO}:latest
                '
                """
            }
        }
    }

    post {
        success {
            echo "🎉 Deployment successful!"
        }
        failure {
            echo "❌ Pipeline failed!"
        }
    }
}

